# Generated by Django 5.0.1 on 2024-01-06 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='descripcion',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='tecnology',
            new_name='technology',
        ),
    ]
